name: pdouvch_sandbox_flutter
description: "A new pdouvch sandbox flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  geolocator: ^12.0.0
  get: ^4.6.6
  google_maps_flutter: ^2.7.0
  provider: ^6.1.2
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  camera: ^0.11.0+1
  google_mlkit_face_detection: ^0.11.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  test: ^1.25.2
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  faker: ^2.1.0

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
